# Application
spring.application.name=car-sharing
server.servlet.context-path=/api

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Stripe
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.public.key=${STRIPE_PUBLIC_KEY}
stripe.success.url=${STRIPE_SUCCESS_URL}
stripe.cancel.url=${STRIPE_CANCEL_URL}

# Telegram
telegram.bot.name=${TELEGRAM_BOT_NAME}
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.chat.id=${TELEGRAM_CHAT_ID}

# Payment
payment.session-id=none
payment.session-url=http://none.none
